Update npm-publish.yml for ci

diff --git a/.github/workflows/npm-publish.yml b/.github/workflows/npm-publish.yml
--- a/.github/workflows/npm-publish.yml
+++ b/.github/workflows/npm-publish.yml
@@ -26,7 +26,7 @@ jobs:
         run: npx stylelint "src/*.css"
 
       - name: Build Minified Files
-        run: npm run build # Ensures dist/ is freshly generated
+        run: npm run build || (echo "Build failed!" && exit 1)
 
       - name: Validate build output
         run: |
